theme: minima
title: The programming blog
author: The Spence
email: smbanasik@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is dedicated to showing off very cool things I find in programming.
  Things such as how to convert strings to integers in C++ for use in switch statements,
  and other things.

# social links
twitter_username: Dont't got one.
github_username:  smbanasik # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
